# Generated by Django 3.2 on 2022-04-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='IIN',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='auditorya_1',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='section_choose',
            field=models.CharField(blank=True, choices=[('1 Секция', '1 Секция'), ('2 Секция', '2 Секция'), ('3 Секция', '3 Секция'), ('4 Секция', '4 Секция'), ('5 Секция', '5 Секция'), ('6 Секция', '6 Секция'), ('7 Секция', '7 Секция'), ('8 Секция', '8 Секция'), ('9 Секция', '9 Секция'), ('10 Секция', '10 Секция'), ('11 Секция', '11 Секция'), ('12 Секция', '12 Секция'), ('13 Секция', '13 Секция'), ('14 Секция', '14 Секция'), ('15 Секция', '15 Секция'), ('16 Секция', '16 Секция'), ('17 Секция', '17 Секция'), ('18 Секция', '18 Секция'), ('19 Секция', '19 Секция'), ('20 Секция', '20 Секция')], default=None, max_length=255, null=True, verbose_name='Секция'),
        ),
    ]
