# Generated by Django 3.2 on 2022-04-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectusers',
            name='status',
        ),
    ]
